# Generated by Django 5.2.3 on 2025-07-01 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
