# Generated by Django 5.2.3 on 2025-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dexterity', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('AR', 'Ambidextrous Right'), ('AL', 'Ambidextrous Left')], default='R', max_length=2)),
                ('golf_dexterity', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('AR', 'Ambidextrous Right'), ('AL', 'Ambidextrous Left')], default='R', max_length=2)),
            ],
        ),
    ]
